yarnPath: .yarn/releases/yarn-4.6.0.cjs
nodeLinker: node-modules
npmRegistryServer: https://registry.yarnpkg.com
npmScopes:
  hibas123:
    npmRegistryServer: https://git.hibas.dev/api/packages/hibas123/npm/
